sudo: false
language: java
jdk:
   - openjdk17
cache:
  directories:
  - $HOME/.m2
  - $HOME/apache-maven-3.8.4

## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - export M2_HOME=$HOME/apache-maven-3.8.4
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH

install: skip

script:  mvn -Drat.ignoreErrors=true --file pom.xml --settings .settings.xml test -Dmaven.javadoc.skip=true -V

deploy:
  # deploy develop 1.0.x to oss
  - provider: script
    skip_cleanup: true
    script: mvn -Drat.ignoreErrors=true --file pom.xml --settings .settings.xml deploy -DskipTests=true -V
    on:
      branch: 1.0.x
  # Push release to oss
  - provider: script
    skip_cleanup: true
    script: mvn -Drat.ignoreErrors=true --file pom.xml --settings .settings.xml deploy -DskipTests=true -Prelease-sign-artifacts -V
    on:
      tags: true